name: Build

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test 

    outputs:
      build_version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Generate Version
        id: version
        run: echo "version=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.version.outputs.version }}
          path: ./dist