name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      build_version:
        description: "Enter build version (e.g. build-v202604162345)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.build_version }}
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist